[versions]
# Plugins
shadow = "8.1.7"

# Mixins
mixin = "0.15.4+mixin.0.8.7"
mixinextras = "0.4.1"

# Tooling
kotlin-coroutines = "1.8.1"
kotlin-serialization = "1.6.3"
guava = "32.1.2-jre"
slf4j = "2.0.9"

# Various
prtree = "1.5"
caffeine = "3.1.8"

# Cloud
cloudCommand = "2.0.0"
cloudMinecraft = "2.0.0-beta.10"

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }

[libraries]
# Tooling
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
prtree = { group = "org.khelekore", name = "prtree", version.ref = "prtree" }

mixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "mixin" }
mixinextras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }

# Cloud
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloudCommand" }
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloudCommand" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloudMinecraft" }

[bundles]
cloud = ["cloud-core", "cloud-annotations", "cloud-paper"]